### ISSUE TITLE
PHPDoc api/classes documentation for IDE integration

### ISSUE THREAD

**Issue by johnny-bit** [WHMCS/developer-docs#175] opened 2020-03-13 19:52 UTC
Current documentation is good(ish) for reading, however it's useless for any IDE integration. Developers can't use any modern IDE features, like checking, typehinting, inline documentation etc that reduces context switching and problems associated.

**Comment by WHMCSMarcus** [comment] 2021-02-18 13:38
Duplicate of #106

**Closed by WHMCSMarcus** 2021-02-18 13:38 UTC
